name: theme_play
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State Management
  get: ^4.6.6
  # Responsive UI
  flutter_screenutil: ^5.9.3
  # Code Generation
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  # Connection Control
  connectivity_plus: ^5.0.2
  # Svg
  flutter_svg: ^2.0.10+1
  # Supabase
  supabase_flutter: ^2.5.8
  # Data Security
  flutter_dotenv: ^5.1.0
  # UI
  flutter_bounceable: ^1.1.0
  popover: ^0.3.0+1
  carousel_slider: ^5.0.0
  showcaseview: ^3.0.0
  # OAuth
  google_sign_in: ^6.2.1
  # Local Storage
  get_storage: ^2.1.1
  # Image
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  # Date format
  intl: ^0.19.0
  # Cancelable Operation
  async: ^2.11.0
  # Animation
  animated_text_kit: ^4.2.2
  # Push Notification
  onesignal_flutter: ^5.2.7
  # Network
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1
  very_good_analysis: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/langs/
    - .env

  fonts:
    - family: Nunito Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Nunito SemiBold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: Nunito Medium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
    - family: Nunito Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
